### ISSUE TITLE
VideoView does not scale correctly (it sclaes for the whole window size / screen size)

### ISSUE THREAD

**Issue by Agredo** [Baseflow/XamarinMediaManager#731] opened 2020-07-13 18:31 UTC
[Sample.zip](https://github.com/Baseflow/XamarinMediaManager/files/4914405/Sample.zip)
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/16531090/87339493-fced1580-c546-11ea-82c7-ee4d96ef232b.png)
![image](https://user-images.githubusercontent.com/16531090/87337706-2a848f80-c544-11ea-8e80-1da0c085655d.png)
![Screenshot_20200713-202308](https://user-images.githubusercontent.com/16531090/87339379-cd3e0d80-c546-11ea-8ba4-31966b0e2a33.png)

it seems the UI is ok in iOS. I Added a sample project.

### Expected behavior

All UI Elements and VideoView Position should be correct

### Configuration
Xamarin.Forms 4.7
Plugin.MediaManager.Forms 0.9,7 - 0.9.8 alpha 2 (crashes for Android 10)

**Platform:** 
- [] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment] 2020-08-11 14:01
Duplicate of https://github.com/Baseflow/XamarinMediaManager/issues/730

**Closed by martijn00** 2020-08-11 14:01 UTC
Labels: bug
