### ISSUE TITLE
Error: This functionality is not implemented in the portable version of this assembly. 

### ISSUE THREAD

**Issue by sahithisk** [Baseflow/XamarinMediaManager#789] opened 2021-02-02 10:37 UTC
I am getting an exception: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

Xamarin.Forms: 4.5.0.667
Plugin.MediaManager:1.0.8
Placed:      CrossMediaManager.Current.Init(); in Main Activity

How to solve this

**Comment by vatttsall** [comment] 2021-02-02 10:44
Getting same issue

**Comment by vatttsall** [comment] 2021-02-02 10:46
Duplicate of #437

**Closed** 2023-01-13 13:10 UTC
